### ISSUE TITLE
Password during registration

### ISSUE THREAD

**Issue by drpikajo** [hoverdroids/PikaPatrol#16]
Request - add a verification field for password during registration and a way to retrieve and/or reset one's password if it is forgotten. From volunteer: "There is only one field (not a verification one) for entering the password. You must look at each letter to verify that it is right before typing the next one, and you cannot see what you typed. Because there is not a second verification field, you might mistype your password and not know what you had actually entered. I am not sure what you would do to reset it if you couldn't get in. Most places where you create a password make you retype it in a second field to verify a match. In addition, there does not seem to be a "forgot password" option to help me access my account again."

**Comment by drpikajo** [comment]
Is there somewhere that these passwords are stored in Firebase that we can access? If so, we can look up the passwords for volunteers. But it does seem like a bit of a problem to never be able to get back in if they lose their password, which I am sure will happen. Such a note could be added to the tutorial page on #39

**Comment by MeganMuellerRMW** [comment]
I like Jo's idea above.  Another option could be to remove the password field altogether.  That seems like an easier fix than doing password verification.  I don't have a good sense for whether people are so used to passwords that they would be reluctant to use an app that has them set up an account with no password.

**Comment by drpikajo** [comment]
Eventually migrate this to log in with Google account - this will solve that issue.

**Comment by drpikajo** [comment]
In the meantime, email us and we can reset their password.

**Comment by MeganMuellerRMW** [comment]
When we eventually migrate this to log in with Google account the following Apple requirement may apply:

"Apps that use a third-party or social login service (such as Facebook Login, Google Sign-In, Sign in with Twitter, Sign In with LinkedIn, Login with Amazon, or WeChat Login) to set up or authenticate the user’s primary account with the app must also offer Sign in with Apple as an equivalent option."  See https://developer.apple.com/app-store/review/guidelines/, section 4.8.  

I thought I'd mention this just in case it makes it more work to migrate to log in with Google.

**Comment by drpikajo** [comment]
#Evilempire
