### ISSUE TITLE
Date issues & observation display

### ISSUE THREAD

**Issue by drpikajo** [hoverdroids/PikaPatrol#19]
Some volunteers had their dates come in as 1/19/70. Some volunteers see different dates on shared observations. One was testing next to her husband and looking at each other's submitted observations: "My husband made one observation (on his app) and when he views it the correct date shows. When I view his observation on my app it shows the date of 1/19/70 and some of the data is missing or incorrect." Another example of entered fields being displayed incorrectly: "I created 1 observation, “observing my cat”, went into airplane mode and tried to create a 2nd observation very cleverly named “observing my cat 2”. Out of airplane mode, I only see observing my cat 2, but with the info from my 1st observation." A few folks had their observations showing up in the 'Shared Observations', but not in 'Your Observations; specifically one volunteer noted that an observation she saved while in service didn't show up in 'Your Observations' but did in 'Shared Observations' whereas another observation that she did offline and then saved again when in service did end up in 'Your Observations.'

**Comment by spragucm** [comment]
@drpikajo @MeganMuellerRMW Let's see if this goes away after the latest updates with the date picker and local observations changes (still working the latter)
