### ISSUE TITLE
Tutorial page for app

### ISSUE THREAD

**Issue by drpikajo** [hoverdroids/PikaPatrol#39]
A few volunteers who were less familiar with mobile apps would have liked for there to be a quick tutorial or other training materials to orient people to the app. From tester: "Consider adding a quick tutorial (that is skippable) when people first open the app? It's fairly intuitive if you play with it for a few minutes but non-tech savvy people may get frustrated initially." We suggest that this be done as a CPP webpage where users can find a video tutorial that is linked in the left menu - if the tutorial is not an easy possibility, then we will take that route.  Here is a link to the CPP page to use for that:  https://pikapartners.org/pika-patrol-tutorials/ - we will make videos once the app features and appearance are finalized.   Let's call it App Help and Info

**Comment by drpikajo** [comment]
I think this could be done VERY easily (and in a way that we can easily modify) by simply adding a link to the webpage above on the menu screen with the list of links. (The link could say: "App Help"). If that requires more than a few lines of code though, then it is not a big deal.

**Comment by MeganMuellerRMW** [comment]
> I think this could be done VERY easily (and in a way that we can easily modify) by simply adding a link to the webpage above on the menu screen with the list of links. (The link could say: "App Help"). If that requires more than a few lines of code though, then it is not a big deal.

Let's make the link say "App Help and Info"
