### ISSUE TITLE
Add a more obvious submit button

### ISSUE THREAD

**Issue by MeganMuellerRMW** [hoverdroids/PikaPatrol#57]
Create a more obvious submit button, rather than the floppy disc save icon.  The floppy disk icon has confused many users.  Add a button at the bottom of the observation page that says “SUBMIT”.  The floppy disk does not need to be removed.

**Comment by spragucm** [comment]
Updated to use check mark and secondary color for the action bar so that the save button is more obvious, without having to add an overlay submit button. Thoughts?

![image](https://github.com/hoverdroids/PikaPatrol/assets/5050589/e046f006-1a33-4e48-bf46-0e312b05dd3c)
